name: Test via npm start

on:
  push:
    branches:
      - main
      - cma
  pull_request:
    branches:
      - main
      - cma

jobs:
  discover-environments:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Discover test environments
        id: set-matrix
        run: |
          env_dirs=$(ls -d environments/* | xargs -n 1 basename)
          matrix=$(echo $env_dirs | jq -cR 'split(" ") | map({environment: .})')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  run-tests:
    needs: discover-environments
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.discover-environments.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: yarn-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-cache-${{ runner.os }}-

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 131
          install-chromedriver: true

      - name: Verify Chrome Version
        run: chrome --version

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: npm test
        working-directory: environments/${{ matrix.environment }}
        env:
          BROWSER: "chrome"
