name: Test via npm start

on:
  push:
    branches:
      - main
      - cma
  pull_request:
    branches:
      - main
      - cma

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: angular
          # - environment: browser-1
          # - environment: browser-2
          # - environment: browser-3
          - environment: gatsbyjs
          - environment: nextjs
          - environment: nextjs-ts
          - environment: node-cjs
          - environment: node-mjs
          - environment: node-ts-cjs
          - environment: node-ts-mjs
          - environment: nuxt
          - environment: react-native-expo
          - environment: rollup
          - environment: svelte
          - environment: vite
          - environment: vite-ts
          - environment: webpack
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: yarn-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ github.ref_name }}
          restore-keys: |
            yarn-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
            yarn-cache-${{ runner.os }}-
            yarn-cache-

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 131
          install-chromedriver: true

      - name: Verify Chrome Version
        run: chrome --version

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: npm test
        working-directory: environments/${{ matrix.environment }}
        env:
          BROWSER: "chrome"
